# baseurl = "http://jdwuarin.github.io/botmaster"
languageCode = "en-us"
title = "Botmaster Documentation"
theme = "hugo-theme-learn"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "JD Wuarin"
	description = "The Bot framework for your serious projects"
	copyright = "MIT"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/jdwuarin/botmaster"

	# version = "2.1.1"
	logo = "images/botmaster.svg"
	favicon = "images/favicon.ico"
	#
	# permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []
	search = true
