# baseurl = "http://jdwuarin.github.io/botmaster/"
baseurl = "http://www.example.com/"
languageCode = "en-us"
title = "Botmaster Documentation"
theme = "hugo-theme-learn"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "JD Wuarin"
	description = "The Bot framework for your serious projects"
	copyright = "MIT"
	editURL = "https://github.com/jdwuarin/botmaster/tree/gh-pages/documentation_website/content/"
	search = true
	menu = [ "home", "getting-started", "working-with-botmaster", "changelog"]
